"""
Diagnosis of preprocessing issue - why pieces aren't separated
"""

import argparse
import os
import sys
import cv2
import numpy as np

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if THIS_DIR not in sys.path:
    sys.path.insert(0, THIS_DIR)

from Puzzle.Extractor import Extractor


def diagnose_preprocessing(image_path):
    """diagnose why pieces aren't being separated."""
    
    print(f"🔍 Preprocessing Diagnosis: {image_path}")
    print("=" * 80)
    
    temp_dir = os.path.join(os.path.dirname(__file__), "debug_preprocessing")
    os.makedirs(temp_dir, exist_ok=True)
    os.environ["ZOLVER_TEMP_DIR"] = temp_dir
    
    img = cv2.imread(image_path, cv2.IMREAD_COLOR)
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    print(f"✓ Image size: {img.shape}")
    
    # Simulate the extractor initialization
    extractor = Extractor(image_path, green_screen=False, factor=0.84)
    bw = extractor.img_bw
    
    print(f"✓ Binary image from extractor:")
    unique_vals = np.unique(bw)
    print(f"   - Unique values: {unique_vals}")
    print(f"   - White pixels: {np.sum(bw == 255)}")
    print(f"   - Black pixels: {np.sum(bw == 0)}")
    
    # Find contours from binary
    contours_raw, _ = cv2.findContours(bw, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    print(f"\n✓ Contours found in binary image: {len(contours_raw)}")
    
    # Check intermediate files generated by extractor
    print(f"\n📂 Checking intermediate images in {temp_dir}...")
    
    if os.path.exists(os.path.join(temp_dir, "simple_bw_filled.png")):
        bw_filled = cv2.imread(os.path.join(temp_dir, "simple_bw_filled.png"), cv2.IMREAD_GRAYSCALE)
        contours_filled, _ = cv2.findContours(bw_filled, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        print(f"   ✓ simple_bw_filled.png: {len(contours_filled)} contours")
        cv2.imwrite(os.path.join(temp_dir, "00_simple_bw_filled.png"), bw_filled)
    
    if os.path.exists(os.path.join(temp_dir, "simple_bw_raw.png")):
        bw_raw = cv2.imread(os.path.join(temp_dir, "simple_bw_raw.png"), cv2.IMREAD_GRAYSCALE)
        contours_raw_file, _ = cv2.findContours(bw_raw, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        print(f"   ✓ simple_bw_raw.png: {len(contours_raw_file)} contours")
        cv2.imwrite(os.path.join(temp_dir, "01_simple_bw_raw.png"), bw_raw)
    
    # Try the actual extraction
    print(f"\n[RUNNING EXTRACTION]")
    pieces = extractor.extract()
    
    if pieces:
        print(f"✓ Extracted {len(pieces)} pieces")
    else:
        print(f"❌ Extraction returned None")
    
    # Visualize the final binary compared to pieces found in simple_piece_threshold
    print(f"\n📊 Summary:")
    print(f"   - cv2.findContours on final binary: {len(contours_raw)} contours")
    print(f"   - simple_piece_threshold found: 6 contours (according to log)")
    print(f"   -Final extraction result: {len(pieces) if pieces else 0} pieces")
    
    print(f"\n💡 Diagnosis:")
    if len(contours_raw) < 6:
        print(f"   ✓ The issue is CONFIRMED: Pieces are merged in the binary image!")
        print(f"   → The pieces are either touching or preprocessingmerged them together")
        print(f"   → simple_piece_threshold handles this better by finding 6 contours")
        print(f"   → But then corner detection fails on at least one piece")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Diagnose preprocessing issues")
    parser.add_argument("--image", required=True, help="Path to puzzle image")
    args = parser.parse_args()
    
    diagnose_preprocessing(args.image)
